name: On Release

on:
  release:
    types: [published]

jobs:
  append-assets:
    name: Append Assets to Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python (or any required setup)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build step (example)
        run: |
          pyinstaller --onefile installer.py ${{ github.event.release.tag_name }}

      - name: Upload Asset to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            dist/installer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
